spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/${DB_NAME:taskdb}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:rootpassword}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
